version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: cloaking-service-mongo
    restart: unless-stopped
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
