version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloaking-service-app
    restart: unless-stopped
    working_dir: /app
    ports:
      - '${SERVER_PORT}:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: cloaking-service-mongo
    restart: unless-stopped
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: cloaking-service-redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  mongo_data:
  redis_data:
