version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: cloaking-service-mongo
    restart: unless-stopped
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: cloaking-service-redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    command:
      [
        'redis-server',
        '--requirepass',
        '${REDIS_PASSWORD}',
        '--appendonly',
        'yes',
      ]

volumes:
  mongo_data:
  redis_data:
